# fly.toml app configuration file generated for quickread on 2023-08-14T12:07:39-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quickread"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
